apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::582031204656:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X2QZ4QWG1ROG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::582031204656:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T10:48:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1905"
  uid: abab031f-4dc2-42ed-9b56-9b10d6246722
